"""Deterministic, dependency-free `strands.Model` for examples and tests.

The stub returns a single text response per invocation, generated by a
caller-supplied function `responder(messages, system_prompt) -> str`.

Why this exists:
  * Real Bedrock requires AWS credentials, network, and is non-deterministic.
  * `examples/two_agent_chat.py` needs a *real* `strands.Agent` to prove that
    CG-ATC sits cleanly above the Strands runtime — but the LLM call itself
    can (and should) be replaceable for CI and reproducibility.
"""

from __future__ import annotations

from collections.abc import AsyncGenerator, AsyncIterable, Callable
from typing import Any

from strands.models.model import Model
from strands.types.content import Messages, SystemContentBlock
from strands.types.streaming import StreamEvent
from strands.types.tools import ToolChoice, ToolSpec


Responder = Callable[[Messages, str | None], str]


def _default_responder(messages: Messages, system_prompt: str | None) -> str:
    last_user = ""
    for m in messages:
        if m.get("role") == "user":
            for block in m.get("content", []):
                if isinstance(block, dict) and "text" in block:
                    last_user = block["text"]
    return f"[stub-reply] heard: {last_user}"


class StubModel(Model):
    """Deterministic stand-in for `strands.models.bedrock.BedrockModel`.

    Yields a Bedrock-style stream that produces a single assistant text
    block.  No network calls, no randomness.
    """

    def __init__(self, *, responder: Responder | None = None,
                 model_id: str = "stub-model-v1") -> None:
        self.model_id = model_id
        self._responder: Responder = responder or _default_responder
        self._config: dict[str, Any] = {"context_window_limit": 8192}

    # ------- Model abstract methods ----------------------------------------
    def update_config(self, **model_config: Any) -> None:
        self._config.update(model_config)

    def get_config(self) -> dict[str, Any]:
        return dict(self._config)

    async def structured_output(
        self, output_model, prompt, system_prompt=None, **kwargs,
    ) -> AsyncGenerator[dict[str, Any], None]:
        # Not used in the chat example, but Model requires it.  We yield a
        # single empty event so awaiting consumers terminate cleanly.
        if False:
            yield {}

    async def stream(
        self,
        messages: Messages,
        tool_specs: list[ToolSpec] | None = None,
        system_prompt: str | None = None,
        *,
        tool_choice: ToolChoice | None = None,
        system_prompt_content: list[SystemContentBlock] | None = None,
        invocation_state: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> AsyncIterable[StreamEvent]:
        text = self._responder(messages, system_prompt)

        # Bedrock-style event stream:
        #   messageStart -> contentBlockStart -> contentBlockDelta(text)
        #   -> contentBlockStop -> messageStop -> metadata
        yield {"messageStart": {"role": "assistant"}}
        yield {"contentBlockStart": {"contentBlockIndex": 0, "start": {}}}
        yield {
            "contentBlockDelta": {
                "contentBlockIndex": 0,
                "delta": {"text": text},
            }
        }
        yield {"contentBlockStop": {"contentBlockIndex": 0}}
        yield {"messageStop": {"stopReason": "end_turn"}}
        yield {
            "metadata": {
                "usage": {"inputTokens": 1, "outputTokens": len(text.split()),
                          "totalTokens": 1 + len(text.split())},
                "metrics": {"latencyMs": 0},
            }
        }
